title: Your awesome title
author: GitHub User
description: >
  tagae's blog.
twitter_username: tagae
github_username: tagae
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
